#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);
my $grep = `grep '%define virtualboxversion' nethserver-virtualbox.spec`;
my ($digits)  = $grep =~ /(\d\.\d)/;
my $event = "nethserver-virtualbox-$digits-VirtualBox-update";

#action
event_actions ( $event, 'initialize-default-databases' => '00');
event_actions ( $event, 'nethserver-virtualbox-create-user-vboxweb' => '10');

foreach $event ( "nethserver-virtualbox-$digits-VirtualBox-update","virtualbox-save") {
    event_actions ( $event, 'nethserver-virtualbox-OracleExtensionPack' => '20');
}
